---
services:
  agent:
    build:
      context: ..
    pull_policy: always
    ports:
      - "8080:8080"
    env_file:
      - .env.agent
    restart: unless-stopped
    networks:
      - a2a-network

  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    env_file:
      - .env.gateway
    restart: unless-stopped
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://agent:8080
    networks:
      - a2a-network
    profiles:
      - manual

networks:
  a2a-network:
    driver: bridge
