apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: documentation-agent
  description: A2A agent server that provides Context7-style documentation capabilities for your agents
  version: 0.2.21
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: true
  card:
    url: "http://localhost:8080"
    documentationUrl: "https://docs.inference-gateway.com"
    protocolVersion: "0.3.0"
    preferredTransport: "JSONRPC"
    defaultInputModes:
      - text
    defaultOutputModes:
      - text
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are an intelligent documentation retrieval assistant that specializes in finding and fetching relevant documentation from Context7-compatible sources. You can resolve library names to their proper identifiers and retrieve targeted documentation based on specific topics or requirements.
    maxTokens: 4096
    temperature: 0.7
  skills:
    - id: resolve_library_id
      name: resolve_library_id
      description: "Resolves library name to Context7-compatible library ID and returns matching libraries"
      tags:
        - docs
        - libraries
      schema:
        type: object
        properties:
          libraryName:
            type: string
            description: "Library name to search for and retrieve a Context7-compatible library ID"
        required:
          - libraryName
      inject:
        - logger
    - id: get_library_docs
      name: get_library_docs
      description: "Fetches up-to-date documentation for a library using Context7-compatible library ID"
      tags:
        - docs
        - libraries
      schema:
        type: object
        properties:
          context7CompatibleLibraryID:
            type: string
            description: "Exact Context7-compatible library ID (e.g., '/mongodb/docs', '/vercel/next.js', '/supabase/supabase') retrieved from resolve_library_id or directly from user query in the format '/org/project' or '/org/project/version'"
          tokens:
            type: number
            description: "Maximum number of tokens of documentation to retrieve (default: 10000). Higher values provide more context but consume more tokens"
          topic:
            type: string
            description: "Topic to focus documentation on (e.g., 'hooks', 'routing')"
        required:
          - context7CompatibleLibraryID
      inject:
        - logger
  server:
    port: 8080
    debug: false
  language:
    go:
      module: "github.com/inference-gateway/documentation-agent"
      version: "1.25.0"
  scm:
    provider: github
    url: "https://github.com/inference-gateway/documentation-agent"
    github_app: true
    issue_templates: true
  sandbox:
    flox:
      enabled: true
