apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: documentation-agent
  description: "Assistant for managing and searching through Documentations queries"
  version: "0.1.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: true
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are a helpful assistant for managing and searching through Documentations queries. You can use MCP Client context7 for searching docs.
    maxTokens: 4096
    temperature: 0.7
  tools:
    - name: resolve_library_id
      description: "Resolves library by its id"
      schema:
        type: object
        properties:
          id:
            - type: string
              description: "Library ID"
        required:
          - id
    - name: get_library_docs
      description: "Get the docs for the specific library"
      schema:
        type: object
        properties:
          library:
            - type: string
              description: "Library Name"
        required:
          - library
  server:
    port: 8080
    debug: false
  language:
    go:
      module: "github.com/inference-gateway/documentation-agent"
      version: "1.24"
  sandbox:
    flox:
      enabled: true
