apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: documentation-agent
  description: "Assistant for managing and searching through Documentations queries"
  version: "0.1.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: true
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are a helpful assistant for managing and searching through Documentations queries. You can use MCP Client context7 for searching docs.
    maxTokens: 4096
    temperature: 0.7
  tools:
    - name: resolve_library_id
      description: "Resolves library name to Context7-compatible library ID and returns matching libraries"
      schema:
        type: object
        properties:
          libraryName:
            type: string
            description: "Library name to search for and retrieve a Context7-compatible library ID"
        required:
          - libraryName
    - name: get_library_docs
      description: "Fetches up-to-date documentation for a library using Context7-compatible library ID"
      schema:
        type: object
        properties:
          context7CompatibleLibraryID:
            type: string
            description: "Exact Context7-compatible library ID (e.g., '/mongodb/docs', '/vercel/next.js', '/supabase/supabase') retrieved from resolve_library_id or directly from user query in the format '/org/project' or '/org/project/version'"
          tokens:
            type: number
            description: "Maximum number of tokens of documentation to retrieve (default: 10000). Higher values provide more context but consume more tokens"
          topic:
            type: string
            description: "Topic to focus documentation on (e.g., 'hooks', 'routing')"
        required:
          - context7CompatibleLibraryID
  server:
    port: 8080
    debug: false
  language:
    go:
      module: "github.com/inference-gateway/documentation-agent"
      version: "1.24"
  sandbox:
    flox:
      enabled: true
