// Code generated by ADL CLI v0.14.1 on 2025-09-03 03:22:17. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/inference-gateway/adk/server"
	"github.com/inference-gateway/adk/server/config"
	"github.com/sethvargo/go-envconfig"
	"go.uber.org/zap"

	"github.com/inference-gateway/documentation-agent/skills"
)

// Config represents the application configuration
type Config struct {
	// Core application settings
	Environment string `env:"ENVIRONMENT"`

	// A2A configuration (all A2A_ prefixed vars)
	A2A config.Config `env:",prefix=A2A_"`
}

var (
	Version          = "0.1.0"
	AgentName        = "documentation-agent"
	AgentDescription = "Assistant for managing and searching through Documentations queries"
)

func main() {
	ctx := context.Background()

	var cfg Config
	if err := envconfig.Process(ctx, &cfg); err != nil {
		log.Fatal("failed to load config:", err)
	}

	var logger *zap.Logger
	var err error
	if cfg.A2A.Debug || cfg.Environment == "dev" || cfg.Environment == "development" {
		logger, err = zap.NewDevelopment()
	} else {
		logger, err = zap.NewProduction()
	}
	if err != nil {
		log.Fatal("failed to initialize logger:", err)
	}
	defer logger.Sync()

	logger.Info("starting documentation-agent agent",
		zap.String("version", Version),
		zap.String("environment", cfg.Environment),
	)
	logger.Debug("loaded configuration")

	toolBox := server.NewDefaultToolBox()

	// Register resolve_library_id skill
	resolveLibraryIDSkill := skills.NewResolveLibraryIDSkill()
	toolBox.AddTool(resolveLibraryIDSkill)
	logger.Info("registered skill", zap.String("skill", "resolve_library_id"), zap.String("description", "Resolves library name to Context7-compatible library ID and returns matching libraries"))

	// Register get_library_docs skill
	getLibraryDocsSkill := skills.NewGetLibraryDocsSkill()
	toolBox.AddTool(getLibraryDocsSkill)
	logger.Info("registered skill", zap.String("skill", "get_library_docs"), zap.String("description", "Fetches up-to-date documentation for a library using Context7-compatible library ID"))

	agent, err := server.NewAgentBuilder(logger).
		WithConfig(&cfg.A2A.AgentConfig).
		WithToolBox(toolBox).
		WithSystemPrompt(`You are a helpful assistant for managing and searching through Documentations queries.
`).
		Build()
	if err != nil {
		logger.Fatal("failed to create agent", zap.Error(err))
	}

	a2aServer, err := server.NewA2AServerBuilder(cfg.A2A, logger).
		WithAgent(agent).
		WithAgentCardFromFile(".well-known/agent.json", map[string]any{
			"name":        AgentName,
			"version":     Version,
			"description": AgentDescription,
			"url":         cfg.A2A.AgentURL,
		}).
		WithDefaultBackgroundTaskHandler().
		WithDefaultStreamingTaskHandler().
		Build()
	if err != nil {
		logger.Fatal("failed to create A2A server", zap.Error(err))
	}

	go func() {
		logger.Info("starting A2A server",
			zap.String("port", cfg.A2A.ServerConfig.Port),
		)
		if err := a2aServer.Start(ctx); err != nil {
			logger.Fatal("server failed to start", zap.Error(err))
		}
	}()

	logger.Info("documentation-agent agent running successfully",
		zap.String("port", cfg.A2A.ServerConfig.Port),
		zap.String("environment", cfg.Environment),
	)

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.Info("shutdown signal received, gracefully stopping server...")
	a2aServer.Stop(ctx)
	logger.Info("documentation-agent agent stopped")
}
